"""Add column seats to fitness_ukassa_processing table

Revision ID: 489b5050018f
Revises: 86b1a541b9a2
Create Date: 2024-08-27 19:51:09.260133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489b5050018f'
down_revision: Union[str, None] = '86b1a541b9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # удаляем все записи
    op.execute("DELETE FROM fitness_ukassa_processing")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fitness_ukassa_processing', sa.Column('seats', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fitness_ukassa_processing', 'seats')
    # ### end Alembic commands ###
