"""update fitenss_ukassa table

Revision ID: 4b1d1eba490d
Revises: ee642451eddd
Create Date: 2024-08-21 12:26:55.826327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1d1eba490d'
down_revision: Union[str, None] = 'ee642451eddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fitness_ukassa', 'back_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fitness_ukassa', 'back_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
