"""update tariffs table

Revision ID: 903dc258ddf4
Revises: 436fc4d3adf8
Create Date: 2024-09-06 10:43:45.097284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903dc258ddf4'
down_revision: Union[str, None] = '436fc4d3adf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fitness_tariffs', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('fitness_tariffs', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('fitness_tariffs', sa.Column('is_new', sa.Boolean(), nullable=False, server_default='false'))

    # conn = op.get_bind()
    # conn.execute("UPDATE fitness_tariffs SET is_new = FALSE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fitness_tariffs', 'is_new')
    op.drop_column('fitness_tariffs', 'end_date')
    op.drop_column('fitness_tariffs', 'start_date')
    # ### end Alembic commands ###
