"""delete and add columns to fitness_ukassa_processing

Revision ID: 9aec408ea1ca
Revises: 928418862f32
Create Date: 2024-08-20 10:40:00.010112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aec408ea1ca'
down_revision: Union[str, None] = '928418862f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fitness_ukassa_processing', sa.Column('payments1C', sa.String(), nullable=False))
    op.drop_column('fitness_ukassa_processing', 'cart')
    op.drop_column('fitness_ukassa_processing', 'promocode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fitness_ukassa_processing', sa.Column('promocode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('fitness_ukassa_processing', sa.Column('cart', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('fitness_ukassa_processing', 'payments1C')
    # ### end Alembic commands ###
