"""Delete column is_base, add column type in fitness_tariff table

Revision ID: 9b314a4fdea1
Revises: 398b7b364c83
Create Date: 2024-08-24 15:55:30.678715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b314a4fdea1'
down_revision: Union[str, None] = '398b7b364c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fitness_tariffs', sa.Column('type', sa.String(), nullable=True))
    op.drop_column('fitness_tariffs', 'is_base')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fitness_tariffs', sa.Column('is_base', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('fitness_tariffs', 'type')
    # ### end Alembic commands ###
