"""update fitness_busy_fictitions_users table

Revision ID: c21c3e84c571
Revises: 9aec408ea1ca
Create Date: 2024-08-20 12:46:16.931930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c21c3e84c571'
down_revision: Union[str, None] = '9aec408ea1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fitness_busy_fictitious_users', sa.Column('appointment_id', sa.String(), nullable=False))
    op.drop_column('fitness_busy_fictitious_users', 'recording')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fitness_busy_fictitious_users', sa.Column('recording', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('fitness_busy_fictitious_users', 'appointment_id')
    # ### end Alembic commands ###
