"""Add promocodes table

Revision ID: d57b573c9dad
Revises: b734c10399a1
Create Date: 2024-10-01 14:42:33.311094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd57b573c9dad'
down_revision: Union[str, None] = 'b734c10399a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fitness_promocodes', sa.Column('widget_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fitness_promocodes', 'widget_id')
    # ### end Alembic commands ###
