"""Add column description to tariffs"

Revision ID: eb1db526e6c4
Revises: 489b5050018f
Create Date: 2024-08-28 13:09:16.598543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb1db526e6c4'
down_revision: Union[str, None] = '489b5050018f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fitness_tariffs', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fitness_tariffs', 'description')
    # ### end Alembic commands ###
