"""Add column description in fitnes table

Revision ID: ee642451eddd
Revises: cf510df56c1a
Create Date: 2024-08-21 11:46:37.267454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee642451eddd'
down_revision: Union[str, None] = 'cf510df56c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fitnes', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('fitness_ukassa', 'back_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fitness_ukassa', 'back_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('fitnes', 'description')
    # ### end Alembic commands ###
