name: Stage Deploy WhiteLabel
on:
  push:
    branches:
      - stage

jobs:
  deploy_stage:
    runs-on: self-hosted
    steps:
      - name: Stage Build
        run: |
          cd /home/ovsergeyev/projects/whitelabel
          git checkout stage
          git pull
          export $(cat .env.stage | xargs)
          docker-compose -f stage-docker-compose.yml stop
          docker-compose -f stage-docker-compose.yml up -d --build