FROM ovsergeyev/logstash:7.5.1
RUN mkdir /usr/share/logstash/logs
COPY ./stage.logstash.yml /usr/share/logstash/config/logstash.yml
COPY ./stage.logstash.conf /usr/share/logstash/pipeline/logstash.conf